services:
  - type: web
    name: michelin-discover-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
